# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci_renesas" "nvme" "xhci_pci" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-030f7704-d3f8-4966-b8ab-b0d695180287";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-030f7704-d3f8-4966-b8ab-b0d695180287".device = "/dev/disk/by-uuid/030f7704-d3f8-4966-b8ab-b0d695180287";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E4E4-1F69";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-43157543-3833-4666-837a-d3de2ecdc7be"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
